// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCox4eY-hdAfkPBaBj59j7nJ_GsK8S_ZAc',
    appId: '1:908367675237:web:216e15e49a1c434c786b8c',
    messagingSenderId: '908367675237',
    projectId: 'kadai-firebase-4527f',
    authDomain: 'kadai-firebase-4527f.firebaseapp.com',
    storageBucket: 'kadai-firebase-4527f.appspot.com',
    measurementId: 'G-6BHN0T7BMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIMUe4YwESKVytgEH7K3cWKTyZBUbm_eo',
    appId: '1:908367675237:android:5e8e8bd45c99144c786b8c',
    messagingSenderId: '908367675237',
    projectId: 'kadai-firebase-4527f',
    storageBucket: 'kadai-firebase-4527f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHe9KH3Ey0_t5T5-hCXPGpBU_LnBx0CfE',
    appId: '1:908367675237:ios:e2ec71363bf974d7786b8c',
    messagingSenderId: '908367675237',
    projectId: 'kadai-firebase-4527f',
    storageBucket: 'kadai-firebase-4527f.appspot.com',
    iosClientId: '908367675237-j6h61bj5ieqovmmva8ujfju74o646l2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
