// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFofJi6yXh7jD44LweRL7hBSaB6MEgkY',
    appId: '1:546811263054:web:bc7c28bcf6bd7c8928ab1f',
    messagingSenderId: '546811263054',
    projectId: 'iamtada-7a08d',
    authDomain: 'iamtada-7a08d.firebaseapp.com',
    storageBucket: 'iamtada-7a08d.appspot.com',
    measurementId: 'G-5K64244TSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDweEJCYxdolxLVLT7-UEdtfQtDGg1QhRs',
    appId: '1:546811263054:android:89ec88765c8115b328ab1f',
    messagingSenderId: '546811263054',
    projectId: 'iamtada-7a08d',
    storageBucket: 'iamtada-7a08d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA79F8__BzkJ8w-VScWZsId09UXYRzHBh0',
    appId: '1:546811263054:ios:db9b77fce65e5fb728ab1f',
    messagingSenderId: '546811263054',
    projectId: 'iamtada-7a08d',
    storageBucket: 'iamtada-7a08d.appspot.com',
    iosClientId:
        '546811263054-042fq9qa9u7jcrqud0ei30sobckg2ugh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA79F8__BzkJ8w-VScWZsId09UXYRzHBh0',
    appId: '1:546811263054:ios:db9b77fce65e5fb728ab1f',
    messagingSenderId: '546811263054',
    projectId: 'iamtada-7a08d',
    storageBucket: 'iamtada-7a08d.appspot.com',
    iosClientId:
        '546811263054-042fq9qa9u7jcrqud0ei30sobckg2ugh.apps.googleusercontent.com',
    iosBundleId: 'com.example.stream',
  );
}
