// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5yAMjMHwPjaz5AUK0kQpAK54sLnC_MKU',
    appId: '1:438781854239:web:6560a1fc6dbf254b330b2a',
    messagingSenderId: '438781854239',
    projectId: 'login-88e7b',
    authDomain: 'login-88e7b.firebaseapp.com',
    storageBucket: 'login-88e7b.appspot.com',
    measurementId: 'G-ZCVQ7F0F8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7YeOYeA2P34uE-4E3h7C_ATa5VY_rxU',
    appId: '1:438781854239:android:5adf4b95d77fb981330b2a',
    messagingSenderId: '438781854239',
    projectId: 'login-88e7b',
    storageBucket: 'login-88e7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxLf34K1wiAq09VqfQOzMwZVVvIiAej8',
    appId: '1:438781854239:ios:8da773824a41c71c330b2a',
    messagingSenderId: '438781854239',
    projectId: 'login-88e7b',
    storageBucket: 'login-88e7b.appspot.com',
    iosClientId:
        '438781854239-dd783aa44hfkvrf4ldqs9alo8skvm2dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxLf34K1wiAq09VqfQOzMwZVVvIiAej8',
    appId: '1:438781854239:ios:8da773824a41c71c330b2a',
    messagingSenderId: '438781854239',
    projectId: 'login-88e7b',
    storageBucket: 'login-88e7b.appspot.com',
    iosClientId:
        '438781854239-dd783aa44hfkvrf4ldqs9alo8skvm2dr.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExercise',
  );
}
