// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbYjnGb15iOM9olrcs7avA8APMVlbJCow',
    appId: '1:839118927830:web:ce7e804eb7c4134de15677',
    messagingSenderId: '839118927830',
    projectId: 'aaaa-2dda3',
    authDomain: 'aaaa-2dda3.firebaseapp.com',
    storageBucket: 'aaaa-2dda3.appspot.com',
    measurementId: 'G-7HQ3581NRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttg7DgKXXpseJYtjHfqeUC4foZPYv2lw',
    appId: '1:839118927830:android:69ba6e59a8aa5c5de15677',
    messagingSenderId: '839118927830',
    projectId: 'aaaa-2dda3',
    storageBucket: 'aaaa-2dda3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXLgrgzLzYwNHu48aIbZLVfcmX6VA3VhE',
    appId: '1:839118927830:ios:d3530a0e11284d72e15677',
    messagingSenderId: '839118927830',
    projectId: 'aaaa-2dda3',
    storageBucket: 'aaaa-2dda3.appspot.com',
    iosClientId:
        '839118927830-7cdkmkhe3ms1j93atpoafj9428u7jpr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
}
